export default [
  { label: "None", temp: false, tempDescription: "" },
  { label: "Bot Initialization", temp: false, tempDescription: "" },
  {
    label: "Message Sent",
    temp: true,
    tempDescription: "Stores the message that was sent",
  },
  {
    label: "On Interval",
    temp: true,
    tempLabel: "Interval of Time (in seconds)",
  },
  { label: "Bot Join Server", temp: false, tempDescription: "" },
  { label: "Bot Leave Server", temp: false, tempDescription: "" },
  {
    label: "Member Join Server",
    temp: true,
    tempDescription: "Stores the member that joined the server",
  },
  {
    label: "Member Leave Server",
    temp: true,
    tempDescription: "Stores the member that left the server",
  },
  {
    label: "Channel Create",
    temp: true,
    tempDescription: "Stores the channel that was created",
  },
  {
    label: "Channel Delete",
    temp: true,
    tempDescription: "Stores the channel that was deleted",
  },
  {
    label: "Role Create",
    temp: true,
    tempDescription: "Stores the role that was created",
  },
  {
    label: "Role Delete",
    temp: true,
    tempDescription: "Stores the role that was deleted",
  },
  {
    label: "Member Banned",
    temp: true,
    tempDescription: "Stores the member that was banned",
  },
  {
    label: "Member Unbanned",
    temp: true,
    tempDescription: "Stores the member that was unbanned",
  },
  {
    label: "Voice Channel Create",
    temp: true,
    tempDescription: "Stores the voice channel that was created",
  },
  {
    label: "Voice Channel Delete",
    temp: true,
    tempDescription: "Stores the voice channel that was deleted",
  },
  {
    label: "Emoji Create",
    temp: true,
    tempDescription: "Stores the emoji that was created",
  },
  {
    label: "Emoji Delete",
    temp: true,
    tempDescription: "Stores the emoji that was deleted",
  },
  {
    label: "Message Deleted",
    temp: true,
    tempDescription: "Stores the message that was deleted",
  },
  {
    label: "Server Update",
    temp: true,
    temp2: true,
    temp2Description: "Stores the server after update",
  },
  {
    label: "Member Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the member prior to update",
    temp2Description: "Stores the member after update",
  },
  {
    label: "Presence Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the member prior to their presence update",
    temp2Description: "Stores the member after their presence update",
  },
  {
    label: "Member Voice Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the member prior to their voice update",
    temp2Description: "Stores the member after their voice update",
  },
  {
    label: "Channel Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the channel prior to update",
    temp2Description: "Stores the channel after update",
  },
  {
    label: "Channel Pins Update",
    temp: true,
    tempDescription: "Stores the channel prior to update",
  },
  {
    label: "Role Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the role prior to update",
    temp2Description: "Stores the role after update",
  },
  {
    label: "Message Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the message prior to update",
    temp2Description: "Stores the message after update",
  },
  {
    label: "Emoji Update",
    temp: true,
    temp2: true,
    tempDescription: "Stores the emoji prior to update",
    temp2Description: "Stores the emoji after update",
  },
  {
    label: "Message Reaction Added",
    temp: true,
    tempDescription: "Stores the message reaction that was added",
  },
  {
    label: "Message Reaction Removed",
    temp: true,
    tempDescription: "Stores the message reaction that was removed",
  },
  {
    label: "All Message Reactions Removed",
    temp: true,
    tempDescription: "Stores the message that had all reactions removed",
  },
  {
    label: "Member Becomes Available",
    temp: true,
    tempDescription: "Stores the member that became available",
  },
  {
    label: "Member Chunck Received",
    temp: true,
    tempDescription: "Stores the members from chunck",
  },
  {
    label: "Member Starts/StopsSpeaking",
    temp: true,
    temp2: true,
    tempDescription: "Stores the member that started/stopped speaking",
    temp2Description:
      "Stores the boolean of whether they started/stopped speaking",
  },
  {
    label: "Member Typing Starts",
    temp: true,
    temp2: true,
    tempDescription: "Stores the channel where member started typing",
    temp2Description: "Stores the member that started typing",
  },
  {
    label: "Member Typing Stops",
    temp: true,
    temp2: true,
    tempDescription: "Stores the channel where member stopped typing",
    temp2Description: "Stores the member that stopped typing",
  },
  {
    label: "Server Becomes Unavailable",
    temp: true,
    tempDescription: "Stores the server that became unavailable",
  },
  {
    label: "On Bot Error",
    temp: true,
    temp2: true,
    tempDescription: "Discord Bot Creator error text",
    temp2Description: "Discord Bot Creator error code",
  },
  {
    label: "On Time Restricted Command",
    temp: true,
    temp2: true,
    tempDescription: "Member that ran the command",
    temp2Description: "Amount of time needed",
  },
];
